### ISSUE TITLE
Item doesn't follow server side dropped item

### ISSUE THREAD

**Issue by xhmr** [Draylar/better-dropped-items#13]
It flows too fast, tries to pop out of the water but it gets dragged back to the ground.

**Comment by Draylar** [comment]
Items now follow their hitboxes pretty accurately in 1.2.4, so I think this issue has been fixed. Let me know if the new result is still not what you were expecting.

**Comment by xhmr** [comment]
@Draylar I will check that when you update on curseforge. 💯

**Comment by Draylar** [comment]
The file just got approved ^^

**Comment by xhmr** [comment]
@Draylar items act pretty much similar + they disappear sometimes.
