### ISSUE TITLE
Update fabric.mod.json to use "depends"

### ISSUE THREAD

**Issue by AshyAspen** [Draylar/better-dropped-items#2]
`[main/WARN]: Mod 'betterdroppeditems' (1.0.1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'`

Minecraft: 1.15.2
Mod version: 1.0.1
Fabric: 0.8.2 Build 194

**Comment by Draylar** [comment]
(was fixed at some point in time, didn't see issue, thanks for report~)
