### ISSUE TITLE
can you update forge version for 1.16.5

### ISSUE THREAD

**Issue by Ariakage** [Draylar/better-dropped-items#26]
can you update forge version for 1.16.5

**Comment by K0-RR** [comment]
![Screenshot from 2021-06-17 13-19-22](https://user-images.githubusercontent.com/43277609/122387190-e75e4800-cf6e-11eb-88aa-53dc9017626b.png)

**Comment by SirOMGitsYOU** [comment]
Use  ItemPhysic Lite on Forge. @chenjj100419
