### ISSUE TITLE
file "betterdroppeditems-1.2.4-1.16.2.jar" it is not support Forge; it is only support Fabric ,so I can't use this mod. "^"

### ISSUE THREAD

**Issue by youchen624** [Draylar/better-dropped-items#32]

**Comment by K0-RR** [comment]
? The whole mod is fabric-only.

**Comment by youchen624** [comment]
? why sort "R" ? "R" isn't Forge? (idk I am not sure what is what

**Comment by Draylar** [comment]
This is a Fabric mod. You can check the required loader for a specific mod file on CurseForge in the area circled in red:

![image](https://user-images.githubusercontent.com/17728338/137359648-51df2f1c-d511-40e7-b832-f1824da3667b.png)

If you want a Forge variant, you might be interested in checking out [ItemPhysic](https://www.curseforge.com/minecraft/mc-mods/itemphysic).

**Comment by youchen624** [comment]
OK
