### ISSUE TITLE
"Mixin apply for mod betterdroppeditems failed"

### ISSUE THREAD

**Issue by EmanYm** [Draylar/better-dropped-items#37]
Launcher: Vanilla Minecraft launcher
Loader: "Preparing to launch minecraft client for fabric-loader-0.13.3-1.18.2"
FabricAPI: 0.48.0

I'm not sure if there is anything else you need to know to reproduce this.

https://pastebin.com/vx96L14d

**Comment by iMoobert** [comment]
I believe I have a similar issue and crash report, if EmanYm's issue was a crash on startup because of having the mod installed

https://pastebin.com/c0SzsDas

**Comment by Draylar** [comment]
1.18.2 & 1.19 support is out now, let me know if you run into this problem again. Thanks!
