### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Gamingkaetzchen** [Draylar/better-dropped-items#38]
When I start my mc with the mot, the following process repeats itself indefinitely.
Game start load mod go to start game start load mod ...

**Comment by istvanmate** [comment]
Same bootloop for me in 1.18.2

**Comment by jayhawker6** [comment]
Same with me. It indefinitely tries to load/download png texture atlases in an infinite bootloop. One of them is chest.png. This only happened in 1.18.2, and it worked fine in 1.18.1 before I updated. Otherwise nothing has changed.

**Comment by jayhawker6** [comment]
@Draylar

**Comment by Draylar** [comment]
Should be fixed now. Thanks for the report!
