### ISSUE TITLE
Found a 1.19 fork:

### ISSUE THREAD

**Issue by Apprisco** [Draylar/better-dropped-items#41]
https://github.com/someone5678/better-dropped-items/releases/tag/1.3.1-1.19
Note that this is obviously not the official release, but it works.

**Comment by someone5678** [comment]
> https://github.com/someone5678/better-dropped-items/releases/tag/1.3.1-1.19 Note that this is obviously not the official release, but it works.

Ohhhhhhh I really eager to find that and gave up. Thx!!!!

**Comment by Draylar** [comment]
1.19 is also out now on CurseForge. Thanks to someone5678 for providing an early fork download!
